### PR TITLE
Merge pull request #1 from bueltge/master

### PR DESCRIPTION
**Pull request by technofreaky**
release new feature in new version

### CODE REVIEW

**Comment by bueltge** [comment]
Why do you have close this pull request?

**Comment by technofreaky** [comment]
Sorry It was wrongly given request ;(

**Comment by bueltge** [comment]
No worries.

**Comment by technofreaky** [comment]
I want to using wordpress defaults model box in post edit page

[wp-admin/post.php?post=368&action=edit]

Model I wanted : Model I wanted

i tried the following instruction in https://codex.wordpress.org/Javascript_Reference/ThickBox

http://i.stack.imgur.com/nGlNK.png

Code I Entered

<div id="my-content-id" style="display:none;">  <p> This is my hidden content! It will appear in ThickBox when the link is clicked. </p>
</div>

I want to control my model with javascript and also needed tab view in that model like

[Media Model ]

Kindly help me to get this done

**Comment by bueltge** [comment]
maybe this helps you -- https://github.com/ocean90/media-modal-demo

**Comment by technofreaky** [comment]
Thanks but i dont need to use this for image listing. i need to add form in it.. and also i need tabs in that like in media popup :) please help me 
i also tried it dose not work

**Comment by bueltge** [comment]
Can you describe, what is your goal. I understand this not really.

**Comment by technofreaky** [comment]
i need a pop like media up loader in post edit page. but its for a form not for listing images

**Comment by technofreaky** [comment]
media
in that popup i need to add html form for it 

i tried using `wp-jquery-ui-dialog` but the output was very bad looking because jquery ui style was applied. not like the media uploader :(

**Comment by bueltge** [comment]
But this can you find in the repository from Dominik, as example.

**Comment by technofreaky** [comment]
i already tried it .. its not working sir :(
can you please help me

**Comment by bueltge** [comment]
No, currently I haven't change this. My last work with the media modal was this plugin: 
https://github.com/bueltge/Multisite-Global-Media

**Comment by technofreaky** [comment]
k thanks . can i add html form in that modal and one thing i dont need any default tabs i need my custom tabs

**Comment by bueltge** [comment]
You should ask on WPSE - http://wordpress.stackexchange.com/
Lot of users, maybe also knowhow in your topic.

**Comment by technofreaky** [comment]
I asked no reply sir

On Wed, Jul 01, 2015 at 4:49 pm, Frank Bültge < notifications@github.com [notifications@github.com] > wrote:
You should ask on WPSE - http://wordpress.stackexchange.com/ [http://wordpress.stackexchange.com/]
Lot of users, maybe also knowhow in your topic.

—
Reply to this email directly or view it on GitHub
[https://github.com/bueltge/WordPress-Admin-Style/pull/29#issuecomment-117614852] .[https://github.com/notifications/beacon/ABzAf-WZQ0vlNm5RlTZcL7jnHfim-8bTks5oY8Q-gaJpZM4FPELp.gif]

**Pull request closed without merging**
